import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BrainCircuit, CheckCircle2, Cloud, ShieldCheck, Sparkles, XCircle } from "lucide-react";
import { useTranslation } from "react-i18next";
import { api } from "../api/client";
import type { AISOCRequestDto } from "../api/types";
import { DetailRow, Drawer, EmptyState, ErrorState, InlineNotice, JsonBlock, LoadingState, MetricCard, Modal, PageHeader, StatusBadge, TableAction, Tag } from "../components/ui";
import { formatDateTime, formatFullDateTime } from "../utils/format";

export default function AISocPage() {
  const { t } = useTranslation();
  const queryClient = useQueryClient();
  const [status, setStatus] = useState("");
  const [selected, setSelected] = useState<AISOCRequestDto | null>(null);
  const [decisionOpen, setDecisionOpen] = useState(false);
  const [decision, setDecision] = useState("ACCEPTED");
  const [reason, setReason] = useState("");
  const policy = useQuery({ queryKey: ["ai-soc-policy"], queryFn: ({ signal }) => api.aiSOCPolicy(signal) });
  const requests = useQuery({ queryKey: ["ai-soc-requests", status], queryFn: ({ signal }) => api.aiSOCRequests({ status, limit: 500 }, signal), refetchInterval: 20_000 });
  const details = useQuery({ queryKey: ["ai-soc-request", selected?.request_id], queryFn: ({ signal }) => api.aiSOCRequest(selected!.request_id, signal), enabled: Boolean(selected) });
  const decide = useMutation({ mutationFn: () => api.decideAISOCRequest(selected!.request_id, { decision, reason: reason.trim() }), onSuccess: () => { setDecisionOpen(false); setReason(""); void queryClient.invalidateQueries({ queryKey: ["ai-soc-request"] }); void queryClient.invalidateQueries({ queryKey: ["ai-soc-requests"] }); } });
  const items = requests.data?.items || [];
  const queued = items.filter((item) => ["QUEUED", "RUNNING"].includes(item.status)).length;
  const blocked = items.filter((item) => item.status === "BLOCKED" || item.prompt_injection_detected).length;
  const current = details.data?.request || selected;

  return <div className="page"><PageHeader eyebrow={t("aiSocPage.eyebrow")} title={t("aiSocPage.title")} subtitle={t("aiSocPage.subtitle")} />
    <section className="metrics-grid compact-metrics"><MetricCard label={t("aiSocPage.requests")} value={requests.data?.total || 0} icon={BrainCircuit} /><MetricCard label={t("aiSocPage.processing")} value={queued} icon={Sparkles} tone={queued ? "warning" : "good"} /><MetricCard label={t("aiSocPage.blocked")} value={blocked} icon={ShieldCheck} tone={blocked ? "critical" : "good"} /><MetricCard label={t("aiSocPage.provider")} value={policy.data?.cloud_allowed ? "LOCAL + CLOUD" : "LOCAL"} icon={Cloud} /></section>
    {policy.isError ? <ErrorState error={policy.error} compact /> : policy.data && <section className="policy-strip panel"><div><span className={`policy-led ${policy.data.enabled ? "on" : ""}`} /><strong>{t("aiSocPage.policy")}</strong><small>v{policy.data.version} · {policy.data.local_model}</small></div><div className="tag-list"><Tag tone={policy.data.enabled ? "accent" : "warning"}>{policy.data.enabled ? t("status.enabled") : t("status.disabled")}</Tag><Tag tone={policy.data.pii_redaction ? "accent" : "warning"}>PII REDACTION</Tag><Tag>{t("aiSocPage.maxContext")}: {policy.data.maximum_context_items}</Tag></div></section>}
    <section className="filter-bar panel"><label className="select-field"><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">{t("common.status")}: {t("common.all")}</option><option>QUEUED</option><option>RUNNING</option><option>SUCCEEDED</option><option>FAILED</option><option>BLOCKED</option></select></label><span className="result-count"><strong>{requests.data?.total || 0}</strong> {t("common.total").toLowerCase()}</span></section>
    <section className="panel table-panel">{requests.isPending ? <LoadingState rows={8} /> : requests.isError ? <ErrorState error={requests.error} onRetry={() => void requests.refetch()} /> : !items.length ? <EmptyState title={t("aiSocPage.noRequests")} icon={BrainCircuit} /> : <div className="table-scroll"><table className="data-table"><thead><tr><th>{t("common.status")}</th><th>{t("aiSocPage.function")}</th><th>{t("aiSocPage.provider")}</th><th>{t("common.confidence")}</th><th>{t("common.actor")}</th><th>{t("common.created")}</th><th /></tr></thead><tbody>{items.map((item) => <tr key={item.request_id} className="clickable-row" onClick={() => setSelected(item)}><td><StatusBadge value={item.status} /></td><td className="primary-cell"><strong>{item.function}</strong><small>{item.question || item.request_id}</small></td><td>{item.provider} / {item.model}</td><td>{item.recommendation?.confidence != null ? `${item.recommendation.confidence}%` : "—"}</td><td>{item.requested_by}</td><td>{formatDateTime(item.created_at)}</td><td><TableAction /></td></tr>)}</tbody></table></div>}</section>
    <Drawer open={Boolean(selected)} onClose={() => setSelected(null)} wide title={current?.function || ""} eyebrow={current?.request_id} footer={current?.status === "SUCCEEDED" && !details.data?.decision ? <button className="button primary" type="button" onClick={() => setDecisionOpen(true)}>{t("aiSocPage.review")}</button> : undefined}>{details.isPending ? <LoadingState rows={6} /> : details.isError ? <ErrorState error={details.error} /> : current && <div className="detail-stack"><div className="drawer-lead"><StatusBadge value={current.status} /><Tag tone="accent">{current.provider}</Tag><strong>{current.question || current.function}</strong></div>{current.prompt_injection_detected && <InlineNotice tone="warning">{t("aiSocPage.injectionDetected")}</InlineNotice>}<dl className="detail-grid"><DetailRow label={t("aiSocPage.model")}>{current.model}</DetailRow><DetailRow label={t("common.actor")}>{current.requested_by}</DetailRow><DetailRow label={t("aiSocPage.redactions")}>{current.redaction_count || 0}</DetailRow><DetailRow label={t("common.created")}>{formatFullDateTime(current.created_at)}</DetailRow></dl>{current.recommendation && <><section className="recommendation-card"><span><Sparkles size={17} />{t("aiSocPage.recommendation")}</span><h3>{current.recommendation.summary}</h3><small>{t("common.confidence")}: {current.recommendation.confidence}%</small></section><RecommendationList title={t("aiSocPage.keyFindings")} items={current.recommendation.key_findings} /><RecommendationList title={t("aiSocPage.investigationSteps")} items={current.recommendation.investigation_steps} ordered /><RecommendationList title={t("aiSocPage.suggestedQueries")} items={current.recommendation.suggested_queries} code />{current.recommendation.limitations?.length > 0 && <RecommendationList title={t("aiSocPage.limitations")} items={current.recommendation.limitations} />}<InlineNotice tone="info">{current.recommendation.disclaimer}</InlineNotice></>}{details.data?.decision && <InlineNotice tone={details.data.decision.decision === "ACCEPTED" ? "success" : "warning"}>{t("aiSocPage.decisionRecorded")}: {details.data.decision.decision} · {details.data.decision.reason}</InlineNotice>}<details className="raw-details"><summary>{t("common.rawData")}</summary><JsonBlock value={details.data} /></details></div>}</Drawer>
    <Modal open={decisionOpen && Boolean(selected)} onClose={() => setDecisionOpen(false)} title={t("aiSocPage.reviewTitle")} footer={<><button className="button ghost" type="button" onClick={() => setDecisionOpen(false)}>{t("common.cancel")}</button><button className="button primary" type="button" disabled={!reason.trim() || decide.isPending} onClick={() => decide.mutate()}>{decision === "ACCEPTED" ? <CheckCircle2 size={16} /> : <XCircle size={16} />}{t("common.save")}</button></>}><label className="form-field"><span>{t("common.decision")}</span><select value={decision} onChange={(event) => setDecision(event.target.value)}><option value="ACCEPTED">{t("common.accept")}</option><option value="REJECTED">{t("common.reject")}</option></select></label><label className="form-field"><span>{t("common.reason")}</span><textarea rows={4} value={reason} onChange={(event) => setReason(event.target.value)} /></label>{decide.isError && <ErrorState error={decide.error} compact />}</Modal>
  </div>;
}

function RecommendationList({ title, items, ordered = false, code = false }: { title: string; items: string[]; ordered?: boolean; code?: boolean }) {
  if (!items?.length) return null;
  const Element = ordered ? "ol" : "ul";
  return <section className="detail-section"><h3>{title}</h3><Element className={`recommendation-list ${code ? "code-list" : ""}`}>{items.map((item, index) => <li key={`${item}-${index}`}>{code ? <code>{item}</code> : item}</li>)}</Element></section>;
}
