import { useDeferredValue, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Archive, Briefcase, CheckCircle2, ClipboardCheck, Link2, MessageSquare, Plus, Search, ShieldAlert, Upload, UserPlus } from "lucide-react";
import { useTranslation } from "react-i18next";
import { api } from "../api/client";
import type { CaseDto, CaseTaskDto } from "../api/types";
import { DetailRow, Drawer, EmptyState, ErrorState, InlineNotice, LoadingState, MetricCard, Modal, PageHeader, SeverityBadge, StatusBadge, TableAction, Tag } from "../components/ui";
import { formatDateTime, formatFullDateTime } from "../utils/format";

export default function CasesPage() {
  const { t } = useTranslation();
  const queryClient = useQueryClient();
  const [search, setSearch] = useState("");
  const [status, setStatus] = useState("");
  const [selected, setSelected] = useState<CaseDto | null>(null);
  const [createOpen, setCreateOpen] = useState(false);
  const [closeOpen, setCloseOpen] = useState(false);
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [incidentID, setIncidentID] = useState("");
  const [closureSummary, setClosureSummary] = useState("");
  const [comment, setComment] = useState("");
  const [taskTitle, setTaskTitle] = useState("");
  const [participant, setParticipant] = useState("");
  const [observableType, setObservableType] = useState("IPV4");
  const [observableValue, setObservableValue] = useState("");
  const [evidenceDescription, setEvidenceDescription] = useState("");
  const deferredSearch = useDeferredValue(search);
  const cases = useQuery({ queryKey: ["cases", deferredSearch, status], queryFn: ({ signal }) => api.cases({ q: deferredSearch, status, limit: 500 }, signal), refetchInterval: 30_000 });
  const incidents = useQuery({ queryKey: ["incidents-for-cases"], queryFn: ({ signal }) => api.incidents({ limit: 500, offset: 0 }, signal) });
  const details = useQuery({ queryKey: ["case", selected?.case_id], queryFn: ({ signal }) => api.case(selected!.case_id, signal), enabled: Boolean(selected) });
  const current = details.data || selected;
  const evidence = useQuery({ queryKey: ["case-evidence", current?.case_id], queryFn: ({ signal }) => api.evidence({ case_id: current!.case_id, limit: 500 }, signal), enabled: Boolean(current) });

  const accept = (item: CaseDto) => {
    setSelected(item);
    queryClient.setQueryData(["case", item.case_id], item);
    void queryClient.invalidateQueries({ queryKey: ["cases"] });
  };
  const createCase = useMutation({ mutationFn: () => api.createCase({ title: title.trim(), description: description.trim(), incident_ids: incidentID ? [incidentID] : [] }), onSuccess: (item) => { accept(item); setCreateOpen(false); setTitle(""); setDescription(""); setIncidentID(""); } });
  const updateCase = useMutation({ mutationFn: (payload: Record<string, unknown>) => api.updateCase(current!.case_id, { ...payload, version: current!.version }), onSuccess: (item) => { accept(item); setCloseOpen(false); setClosureSummary(""); } });
  const addComment = useMutation({ mutationFn: () => api.addCaseComment(current!.case_id, comment.trim(), current!.version), onSuccess: (item) => { accept(item); setComment(""); } });
  const addTask = useMutation({ mutationFn: () => api.addCaseTask(current!.case_id, { title: taskTitle.trim(), version: current!.version }), onSuccess: (item) => { accept(item); setTaskTitle(""); } });
  const updateTask = useMutation({ mutationFn: (task: CaseTaskDto) => api.updateCaseTask(current!.case_id, task.task_id, { status: "DONE", version: current!.version }), onSuccess: accept });
  const addParticipant = useMutation({ mutationFn: () => api.addCaseParticipant(current!.case_id, { user_id: participant.trim(), role: "MEMBER", version: current!.version }), onSuccess: (item) => { accept(item); setParticipant(""); } });
  const addObservable = useMutation({ mutationFn: () => api.addCaseObservable(current!.case_id, { type: observableType, value: observableValue.trim(), source: "analyst", version: current!.version }), onSuccess: (item) => { accept(item); setObservableValue(""); } });
  const uploadEvidence = useMutation({ mutationFn: (file: File) => api.uploadCaseEvidence(current!.case_id, file, evidenceDescription.trim()), onSuccess: () => { setEvidenceDescription(""); void queryClient.invalidateQueries({ queryKey: ["case-evidence"] }); void queryClient.invalidateQueries({ queryKey: ["case"] }); } });

  const items = cases.data?.items || [];
  const openCount = items.filter((item) => item.status !== "CLOSED").length;
  const overdue = items.filter((item) => item.sla?.breached || (item.status !== "CLOSED" && new Date(item.sla?.due_at || 0).getTime() < Date.now())).length;
  const taskCount = items.reduce((sum, item) => sum + (item.tasks?.filter((task) => task.status !== "DONE" && task.status !== "CANCELLED").length || 0), 0);

  return <div className="page"><PageHeader eyebrow={t("casesPage.eyebrow")} title={t("casesPage.title")} subtitle={t("casesPage.subtitle")} actions={<button className="button primary" type="button" onClick={() => setCreateOpen(true)}><Plus size={16} />{t("casesPage.create")}</button>} />
    <section className="metrics-grid compact-metrics"><MetricCard label={t("casesPage.total")} value={cases.data?.total || 0} icon={Briefcase} /><MetricCard label={t("casesPage.open")} value={openCount} icon={ShieldAlert} tone={openCount ? "warning" : "good"} /><MetricCard label={t("casesPage.overdue")} value={overdue} icon={ClipboardCheck} tone={overdue ? "critical" : "good"} /><MetricCard label={t("casesPage.openTasks")} value={taskCount} icon={CheckCircle2} /></section>
    <section className="filter-bar panel"><label className="search-field grow"><Search size={17} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder={t("casesPage.searchPlaceholder")} /></label><label className="select-field"><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">{t("common.status")}: {t("common.all")}</option><option>OPEN</option><option>INVESTIGATION</option><option>RESPONSE</option><option>CLOSED</option></select></label></section>
    <section className="panel table-panel">{cases.isPending ? <LoadingState rows={8} /> : cases.isError ? <ErrorState error={cases.error} onRetry={() => void cases.refetch()} /> : !items.length ? <EmptyState title={t("casesPage.noCases")} icon={Briefcase} /> : <div className="table-scroll"><table className="data-table"><thead><tr><th>{t("common.status")}</th><th>{t("common.severity")}</th><th>{t("common.title")}</th><th>{t("casesPage.owner")}</th><th>{t("casesPage.relatedIncidents")}</th><th>{t("casesPage.sla")}</th><th>{t("common.updated")}</th><th /></tr></thead><tbody>{items.map((item) => <tr key={item.case_id} className="clickable-row" onClick={() => setSelected(item)}><td><StatusBadge value={item.status} /></td><td><SeverityBadge value={item.severity} /></td><td className="primary-cell"><strong>{item.title}</strong><small>{item.case_id}</small></td><td>{item.owner}</td><td>{item.incident_ids?.length || 0}</td><td><StatusBadge value={item.sla?.breached ? "BREACHED" : "ON_TRACK"} /></td><td>{formatDateTime(item.updated_at)}</td><td><TableAction /></td></tr>)}</tbody></table></div>}</section>

    <Drawer open={Boolean(selected)} onClose={() => setSelected(null)} wide title={current?.title || ""} eyebrow={current?.case_id} footer={current && current.status !== "CLOSED" ? <div className="action-row align-right">{current.allowed_transitions?.map((next) => <button key={next} className={next === "CLOSED" ? "button ghost" : "button primary"} type="button" disabled={updateCase.isPending} onClick={() => next === "CLOSED" ? setCloseOpen(true) : updateCase.mutate({ status: next })}>{t("casesPage.moveTo", { status: next })}</button>)}</div> : undefined}>
      {details.isPending ? <LoadingState rows={7} /> : details.isError ? <ErrorState error={details.error} /> : current && <div className="detail-stack"><div className="drawer-lead"><StatusBadge value={current.status} /><SeverityBadge value={current.severity} /><strong>{current.title}</strong></div><p className="lead-description">{current.description || t("common.notAvailable")}</p><dl className="detail-grid"><DetailRow label={t("casesPage.owner")}>{current.owner}</DetailRow><DetailRow label={t("casesPage.sla")}>{formatFullDateTime(current.sla?.due_at)}</DetailRow><DetailRow label={t("common.created")}>{formatFullDateTime(current.created_at)}</DetailRow><DetailRow label={t("common.updated")}>{formatFullDateTime(current.updated_at)}</DetailRow></dl>
        <section className="detail-section"><h3>{t("casesPage.relatedIncidents")}</h3><div className="tag-list">{current.incident_ids?.length ? current.incident_ids.map((id) => <Tag key={id} tone="accent"><Link2 size={12} />{id}</Tag>) : <span className="muted">{t("common.noData")}</span>}</div></section>
        <section className="detail-section"><h3>{t("casesPage.tasks")}</h3><div className="case-command"><input value={taskTitle} onChange={(event) => setTaskTitle(event.target.value)} placeholder={t("casesPage.taskPlaceholder")} /><button className="button secondary" type="button" disabled={!taskTitle.trim() || addTask.isPending} onClick={() => addTask.mutate()}><Plus size={14} />{t("casesPage.addTask")}</button></div>{current.tasks?.length ? <div className="case-task-list">{current.tasks.map((task) => <div key={task.task_id}><button className={`task-check ${task.status === "DONE" ? "done" : ""}`} type="button" disabled={task.status === "DONE" || updateTask.isPending} onClick={() => updateTask.mutate(task)}><CheckCircle2 size={17} /></button><div><strong>{task.title}</strong><small>{task.assignee || t("common.unassigned")} · {formatDateTime(task.due_at)}</small></div><StatusBadge value={task.status} /></div>)}</div> : <EmptyState title={t("casesPage.noTasks")} icon={CheckCircle2} />}</section>
        <section className="detail-section"><h3>{t("casesPage.participants")}</h3><div className="case-command"><input value={participant} onChange={(event) => setParticipant(event.target.value)} placeholder={t("casesPage.participantPlaceholder")} /><button className="button secondary" type="button" disabled={!participant.trim() || addParticipant.isPending} onClick={() => addParticipant.mutate()}><UserPlus size={14} />{t("common.apply")}</button></div><div className="tag-list">{current.participants?.map((value) => <Tag key={value.user_id}>{value.user_id} · {value.role}</Tag>)}</div></section>
        <section className="detail-section"><h3>{t("casesPage.observables")}</h3><div className="case-command observable-command"><select value={observableType} onChange={(event) => setObservableType(event.target.value)}><option>IPV4</option><option>DOMAIN</option><option>URL</option><option>HASH</option><option>EMAIL</option></select><input value={observableValue} onChange={(event) => setObservableValue(event.target.value)} placeholder={t("casesPage.observablePlaceholder")} /><button className="button secondary" type="button" disabled={!observableValue.trim() || addObservable.isPending} onClick={() => addObservable.mutate()}><Plus size={14} />{t("common.apply")}</button></div><div className="compact-list">{current.observables?.map((value) => <div key={value.observable_id}><div><strong>{value.value}</strong><small>{value.source || "—"}</small></div><Tag tone="accent">{value.type}</Tag></div>)}</div></section>
        <section className="detail-section"><h3>{t("casesPage.evidence")}</h3><div className="evidence-upload"><label className="form-field"><span>{t("common.description")}</span><input value={evidenceDescription} onChange={(event) => setEvidenceDescription(event.target.value)} /></label><label className="button secondary file-button"><Upload size={15} />{t("casesPage.attachEvidence")}<input type="file" disabled={uploadEvidence.isPending} onChange={(event) => { const file = event.target.files?.[0]; if (file) uploadEvidence.mutate(file); event.target.value = ""; }} /></label></div>{uploadEvidence.isError && <ErrorState error={uploadEvidence.error} compact />}{uploadEvidence.isSuccess && <InlineNotice tone="success">{t("casesPage.evidenceAttached")}</InlineNotice>}{evidence.isPending ? <LoadingState rows={3} compact /> : evidence.data?.items.length ? <div className="compact-list">{evidence.data.items.map((item) => <div key={item.evidence_id}><div><strong>{item.filename}</strong><small>{item.sha256.slice(0, 20)}…</small></div><StatusBadge value={item.status} /></div>)}</div> : <EmptyState title={t("casesPage.noEvidence")} icon={Archive} />}</section>
        <section className="detail-section"><h3>{t("casesPage.comments")}</h3><div className="case-command"><input value={comment} onChange={(event) => setComment(event.target.value)} placeholder={t("casesPage.commentPlaceholder")} /><button className="button secondary" type="button" disabled={!comment.trim() || addComment.isPending} onClick={() => addComment.mutate()}><MessageSquare size={14} />{t("casesPage.addComment")}</button></div><div className="case-comments">{current.comments?.map((value) => <article key={value.comment_id}><strong>{value.author}</strong><p>{value.body}</p><small>{formatFullDateTime(value.created_at)}</small></article>)}</div></section>
        <section className="detail-section"><h3>{t("casesPage.history")}</h3><div className="timeline">{current.history?.map((entry) => <div key={entry.history_id}><span className="timeline-dot" /><div><strong>{entry.action}</strong><p>{entry.message}</p><small>{formatFullDateTime(entry.created_at)} · {entry.actor}</small></div></div>)}</div></section>
        {current.closure_summary && <InlineNotice tone="info">{t("casesPage.closureSummary")}: {current.closure_summary}</InlineNotice>}
      </div>}
    </Drawer>

    <Modal open={createOpen} onClose={() => setCreateOpen(false)} title={t("casesPage.createTitle")} footer={<><button className="button ghost" type="button" onClick={() => setCreateOpen(false)}>{t("common.cancel")}</button><button className="button primary" type="button" disabled={!title.trim() || createCase.isPending} onClick={() => createCase.mutate()}><Briefcase size={16} />{t("casesPage.create")}</button></>}><label className="form-field"><span>{t("common.title")}</span><input value={title} onChange={(event) => setTitle(event.target.value)} /></label><label className="form-field"><span>{t("common.description")}</span><textarea rows={4} value={description} onChange={(event) => setDescription(event.target.value)} /></label><label className="form-field"><span>{t("casesPage.relatedIncident")}</span><select value={incidentID} onChange={(event) => setIncidentID(event.target.value)}><option value="">{t("common.notAvailable")}</option>{incidents.data?.items.map((incident) => <option key={incident.id} value={incident.id}>{incident.title || incident.id}</option>)}</select></label>{createCase.isError && <ErrorState error={createCase.error} compact />}</Modal>
    <Modal open={closeOpen && Boolean(current)} onClose={() => setCloseOpen(false)} title={t("casesPage.closeTitle")} footer={<><button className="button ghost" type="button" onClick={() => setCloseOpen(false)}>{t("common.cancel")}</button><button className="button primary" type="button" disabled={!closureSummary.trim() || updateCase.isPending} onClick={() => updateCase.mutate({ status: "CLOSED", closure_summary: closureSummary.trim() })}><CheckCircle2 size={16} />{t("common.close")}</button></>}><p className="modal-intro">{t("casesPage.closeHint")}</p><label className="form-field"><span>{t("casesPage.closureSummary")}</span><textarea rows={5} value={closureSummary} onChange={(event) => setClosureSummary(event.target.value)} /></label>{updateCase.isError && <ErrorState error={updateCase.error} compact />}</Modal>
  </div>;
}
